CREATE TABLE tabla_1 (a INTEGER, b CHAR(10));

ALTER TABLE tabla_1;
RENAME TABLE tabla_1 to tabla_2;

ALTER TABLE tabla_2
MODIFY COLUMN a TINYINT NOT NULL;

ALTER TABLE tabla_2
CHANGE COLUMN b c CHAR(20);

ALTER TABLE tabla_2
ADD COLUMN d TIMESTAMP;

ALTER TABLE tabla_2
DROP COLUMN c;

CREATE TABLE tabla_3 AS
SELECT *
FROM tabla_2;

DROP TABLE IF EXISTS tabla_2;

ALTER TABLE tabla_3;
RENAME TABLE tabla_3 to tabla_1;


